language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - dist: xenial
      python: 3.7


install:
  - pip install dpkt
  - python setup.py install
  - sudo iptables -A INPUT -j NFQUEUE -i lo --dst 127.0.0.2 --queue-num 1

before_script: cd test

script:
  - sudo `which python` ping_test.py
  - sudo `which python` flood_test.py short
