name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install dpkt
    - name: Build+install package
      run: |
        python setup.py install
    - name: setup nfqueue
      run: sudo iptables -A INPUT -j NFQUEUE -i lo --dst 127.0.0.2 --queue-num 1
    - name: run tests
      working-directory: test
      run: |
        sudo `which python` ping_test.py
        sudo `which python` flood_test.py short
        sudo `which python` close_test.py short
