name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install dpkt
    - name: Build+install package
      run: |
        python setup.py install
    - name: setup nfqueue
      run: sudo iptables -A INPUT -j NFQUEUE -i lo --dst 127.0.0.2 --queue-num 1
    - name: run tests
      working-directory: test
      run: |
        sudo `which python` ping_test.py
        sudo `which python` flood_test.py short
        sudo `which python` close_test.py short
